
services:
  gateway:
    build:
      context: .
      dockerfile: ApiGateway.Dockerfile
    image: "microservice/api-gateway:latest"
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - order-service
      - product-service
    networks:
      - app_network

  auth-service:
    build:
      context: .
      dockerfile: AuthApi.Dockerfile
    image: "microservice/auth-service:latest"
    networks:
      - app_network

  order-service:
    build:
      context: .
      dockerfile: OrderApi.Dockerfile  
    image: "microservice/order-service:latest"
    networks:
      - app_network

  product-service:
    build:
      context: .
      dockerfile: ProductApi.Dockerfile
    image: "microservice/product-service:latest"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
