services:
  gateway:
    build:
      context: .
      dockerfile: ApiGateway.Dockerfile
    image: "e-commerce/api-gateway:latest"
    container_name: "ECommerce.ApiGateway"
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - order-service
      - product-service
      - consul
    networks:
      - app_network

  auth-service:
    build:
      context: .
      dockerfile: AuthApi.Dockerfile
    image: "e-commerce/auth-service:latest"
    container_name: "ECommerce.AuthService"
    depends_on:
      - consul
    networks:
      - app_network

  order-service:
    build:
      context: .
      dockerfile: OrderApi.Dockerfile  
    image: "e-commerce/order-service:latest"
    container_name: "ECommerce.OrderService"
    depends_on:
      - consul
    networks:
      - app_network

  product-service:
    build:
      context: .
      dockerfile: ProductApi.Dockerfile
    image: "e-commerce/product-service:latest"
    container_name: "ECommerce.ProductService"
    depends_on:
      - consul
    networks:
      - app_network

  consul:
    image: "hashicorp/consul:latest"
    container_name: "ECommerce.Consul"
    ports:
      - 8500:8500
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
